version: "3.9"
services:
    api:
        build: ./saleCar/
        command: ./manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./server/api:/code/
        ports:
            - 8000:8000